name: Wisecow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t bhavani2909/wisecow:latest ./wisecow

    # 5️⃣ Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push bhavani2909/wisecow:latest

    # 6️⃣ Set up Kubeconfig for Minikube / Kubernetes cluster
    - name: Set up Kubeconfig
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 7️⃣ Apply Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./wisecow/wisecow-deployment.yaml
        kubectl apply -f ./wisecow/wisecow-service.yaml
        kubectl apply -f ./wisecow/wisecow-ingress.yaml

